server:
  port: 8082

spring:
  application:
    name: auth-service
  # profiles:
  #   active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5433}/${POSTGRES_DB_NAME:auth_db}
    username: ${POSTGRES_DB_USERNAME:postgres}
    password: ${POSTGRES_DB_PASSWORD:SenhaSuperSegura123!}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

# 📊 Métrica e Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

# Swagger / OpenAPI customizado para o time de desenvolvimento
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Chaves RSA Privada/Pública para assinatura dos Tokens JWT
jwt:
  private-key-path: classpath:certs/app.key
  public-key-path: classpath:certs/app.pub
  expiration-ms: 86400000

logging:
  level:
    root: INFO # Nível geral do ecossistema (Spring, Hibernate, etc.)
    com.auth: DEBUG # Nível detalhado para o seu código
    # org.hibernate.SQL: DEBUG # Exibe as queries SQL no console
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
