server:
  port: 8082

spring:
  application:
    name: auth-service
  # profiles:
  #   active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5433}/${POSTGRES_DB_NAME:auth_db}
    username: ${POSTGRES_DB_USERNAME:postgres}
    password: ${POSTGRES_DB_PASSWORD:SenhaSuperSegura123!}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

# 📊 Observabilidade
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0 # 100% de amostragem de rastros
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317} # Endpoint onde o Grafana Tempo recebe rastros OTLP
  prometheus:
    metrics:
      export:
        enabled: true

# Configuração do padrão do Log no Console
logging:
  pattern: 
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

# Swagger / OpenAPI customizado para o time de desenvolvimento
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Chaves RSA Privada/Pública para assinatura dos Tokens JWT
jwt:
  private-key-path: classpath:certs/app.key
  public-key-path: classpath:certs/app.pub
  expiration-ms: 86400000

