services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SenhaSuperSegura123!
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - bff_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db && psql -U postgres -d auth_db -c \"SELECT 1 FROM pg_database WHERE datname = 'inventory_db'\" | grep -q 1 || psql -U postgres -d auth_db -c \"CREATE DATABASE inventory_db;\""]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: inventory_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: SenhaSuperSegura123!
    ports:
      - "27018:27017"
    volumes:
      - bff_mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "-u", "admin", "-p", "SenhaSuperSegura123!", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_DB_NAME=auth_db
      - POSTGRES_DB_USERNAME=postgres
      - POSTGRES_DB_PASSWORD=SenhaSuperSegura123!
      - POSTGRES_DB_PORT=5432
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8082 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  inventory-control-system:
    build:
      context: ../inventory-control-system
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      # Variáveis do Postgres
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_DB_NAME=inventory_db
      - POSTGRES_DB_USERNAME=postgres
      - POSTGRES_DB_PASSWORD=SenhaSuperSegura123!
      - POSTGRES_DB_PORT=5432
      # Variáveis do MongoDB
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=SenhaSuperSegura123!
      - MONGO_DB_NAME=inventory_db
      - MONGO_AUTH_DB=admin
      # Configurações do Hibernate
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8081 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  bff_postgres_data:
  bff_mongo_data:
