services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SenhaSuperSegura123!
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db && psql -U postgres -d auth_db -c \"SELECT 1 FROM pg_database WHERE datname = 'product_db'\" | grep -q 1 || psql -U postgres -d auth_db -c \"CREATE DATABASE product_db;\""]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_db_data:/var/lib/postgresql/data
    networks:
      - inventory-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=auth_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=SenhaSuperSegura123!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JAVA_TOOL_OPTIONS=-Dmanagement.metrics.binders.processor.enabled=false
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - inventory-network

  # inventory-control-system:
  #   build:
  #     context: ./inventory-control-system
  #     dockerfile: Dockerfile
  #   container_name: inventory-control-system
  #   ports:
  #     - "8081:8081"
  #   environment:
      # - DB_HOST=postgres-db
      # - DB_NAME=product_db
      # - DB_USERNAME=postgres
      # - DB_PASSWORD=SenhaSuperSegura123!
      # - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #   depends_on:
  #     postgres-db:
  #       condition: service_healthy
  #   networks:
  #     - inventory-network

  inventory-control-web-system:
    build:
      context: ./inventory-control-web-system
      dockerfile: Dockerfile
    container_name: inventory-control-web-system
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8082
      # - INVENTORY_CONTROL_SYSTEM_URL=http://inventory-control-system:8081
    depends_on:
      - auth-service
      # - inventory-control-system
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  pg_db_data:
