server:
  port: 8080

application:
  name: inventory-control-web-system
  feign:
    inventory-control-system:
      url: ${INVENTORY_CONTROL_SYSTEM_URL:http://localhost:8081}
    auth-service:
      url: ${AUTH_SERVICE_URL:http://localhost:8082}

# 📊 Observabilidade
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0 # 100% de amostragem de rastros
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317} # Endpoint onde o Grafana Tempo recebe rastros OTLP
  prometheus:
    metrics:
      export:
        enabled: true

# Configuração do padrão do Log no Console
logging:
  pattern: 
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
      
jwt:
  public-key-path: classpath:certs/app.pub 
