server:
  port: 8080

application:
  name: inventory-control-web-system
  feign:
    inventory-control-system:
      url: ${INVENTORY_CONTROL_SYSTEM_URL:http://localhost:8081}
    auth-service:
      url: ${AUTH_SERVICE_URL:http://localhost:8082}

# Configuração detalhada do log para depurar chamadas HTTP se necessário
logging:
  level:
    com.inventory.control.web.system.infrastructure.integration.client: DEBUG

jwt:
  public-key-path: classpath:certs/app.pub 