CREATE TABLE tb_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    
    CONSTRAINT uk_tb_categories_name UNIQUE (name)
);

CREATE TABLE tb_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL,
    name VARCHAR(255) NULL,
    description VARCHAR(255) NULL,
    price DECIMAL(19, 2) NULL,
    quantity INT NULL,
    category_id BIGINT NULL,

    CONSTRAINT uk_tb_products_sku UNIQUE (sku),
    CONSTRAINT fk_tb_products_category FOREIGN KEY (category_id) REFERENCES tb_categories(id)
);

INSERT INTO tb_categories (name, description)
SELECT 'Eletrônicos', 'Dispositivos eletrônicos, componentes e acessórios'
WHERE NOT EXISTS (SELECT 1 FROM tb_categories WHERE name = 'Eletrônicos');

INSERT INTO tb_categories (name, description)
SELECT 'Periféricos', 'Teclados, mouses, monitores e periféricos de informática'
WHERE NOT EXISTS (SELECT 1 FROM tb_categories WHERE name = 'Periféricos');

INSERT INTO tb_categories (name, description)
SELECT 'Móveis de Escritório', 'Cadeiras ergonômicas, mesas e organizadores'
WHERE NOT EXISTS (SELECT 1 FROM tb_categories WHERE name = 'Móveis de Escritório');

INSERT INTO tb_categories (name, description)
SELECT 'Acessórios de Rede', 'Cabos, roteadores, switches e adaptadores'
WHERE NOT EXISTS (SELECT 1 FROM tb_categories WHERE name = 'Acessórios de Rede');