spring:
  # Logs de SQL para depuração em ambiente local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Nível de Log detalhado para o ecossistema do seu app
logging:
  level:
    com.inventory.control.system: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    
# Desativa spring secury
app:
  security:
    enabled: false